import type { Metadata } from "next";
import { Poppins, Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "../../../lib/storeProvider";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ReactNode } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});
const mont = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
  params: { locale: string };
};

export default async function RootLayout({
  children,
  params: { locale },
}: LayoutProps) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={` ${mont.variable}
        ${poppins.variable}
        antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            <div className="">{children}</div>
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
