name: Deploy to Droplet

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the deployment job
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Step 1: Checkout the repository code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # Step 2: Set up SSH agent for secure authentication
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to the Droplet via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}       
          username: ${{ secrets.DEPLOY_USER }}  
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/grantsconsult-frontend/ 
            echo "Pulling the latest changes from GitHub"
            
            # Pull the latest changes from the main branch
            git fetch origin main
            git reset --hard origin/main

            # Start a new PM2 process for the frontend
            echo "Reloading PM2 process for grantsconsult-frontend"
            pm2 restart grantsconsult-frontend
