name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}       
          username: ${{ secrets.DEPLOY_USER }}  
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/grants-consult/
            echo "Pulling the latest changes from GitHub..."
            git pull origin main
            echo "Checking restarting the grantsconsult service on the server"
            sudo systemctl restart grantsconsult.service
